# Generated by Django 2.0.9 on 2025-11-24 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('proof', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='m_notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('prediction_type', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='v_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=500)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
            ],
        ),
    ]
